[package]
name = "binance-rust-cli"
version = "0.1.0"
authors = ["Eric <eric.abrahams@e-systemsconsulting.com>"]

[dependencies]
reqwest = "0.8.1"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
